(defun print-str (p)
  (setq c (load-byte p))
  (loop c
    (putc c)
    (setq p (+ p 1))
    (setq c (load-byte p))))

; Read a line (until '\n') into buf; NUL-terminate; return buf address.
(defun read-str (buf)
  (setq p buf)
  (setq c (getc))
  (loop (- c 10)
    (store-byte p c)
    (setq p (+ p 1))
    (setq c (getc)))
  (store-byte p 0)
  buf)

(setq name-buf 512)
(print-str "What is your name?\n")
(read-str name-buf)
(print-str "Hello, ")
(print-str name-buf)
(putc 33)
(putc 10)
